# Generated by Django 3.2.10 on 2021-12-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='anh',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='mota',
            field=models.CharField(default=None, max_length=200000),
        ),
    ]
